name: expensetracker
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  firebase_core: ^3.15.2
  firebase_auth: ^5.6.3
  cloud_firestore: ^5.6.12
  google_sign_in: ^6.3.0
  image_picker: ^1.1.2
  google_mlkit_text_recognition: ^0.15.0
  web: ^1.1.1
  url_launcher: ^6.3.1
  intl: ^0.18.1
  fl_chart: ^0.66.0
  google_generative_ai: ^0.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: icon.png
  remove_alpha_ios: true
  min_sdk_android: 21
  web:
    generate: true
    image_path: icon.png
    background_color: "#ffffff"
    theme_color: "#0175C2"
  windows:
    generate: true
    image_path: icon.png
    icon_size: 48
  macos:
    generate: true
    image_path: icon.png
