// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk18G1nOGcFSstqgTdkXNuMpPzxNllC4U',
    appId: '1:920582359516:web:86543caf008a438f36e719',
    messagingSenderId: '920582359516',
    projectId: 'th5-mobile-4754a',
    authDomain: 'th5-mobile-4754a.firebaseapp.com',
    storageBucket: 'th5-mobile-4754a.firebasestorage.app',
    measurementId: 'G-RD91QQQGYM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8xmLF0oz7OOUl9ME8O51Y3kdRn0t4BCE',
    appId: '1:920582359516:android:eee2f9b029a1a70d36e719',
    messagingSenderId: '920582359516',
    projectId: 'th5-mobile-4754a',
    storageBucket: 'th5-mobile-4754a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2f5HzCTiLK1p4U6UIuD7Lot3wa-oSJJ0',
    appId: '1:920582359516:ios:9668638a6500cc8f36e719',
    messagingSenderId: '920582359516',
    projectId: 'th5-mobile-4754a',
    storageBucket: 'th5-mobile-4754a.firebasestorage.app',
    iosClientId: '920582359516-c6jlq418b0bhkg36c3pn9iu6805bjulg.apps.googleusercontent.com',
    iosBundleId: 'com.example.expensetracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2f5HzCTiLK1p4U6UIuD7Lot3wa-oSJJ0',
    appId: '1:920582359516:ios:9668638a6500cc8f36e719',
    messagingSenderId: '920582359516',
    projectId: 'th5-mobile-4754a',
    storageBucket: 'th5-mobile-4754a.firebasestorage.app',
    iosClientId: '920582359516-c6jlq418b0bhkg36c3pn9iu6805bjulg.apps.googleusercontent.com',
    iosBundleId: 'com.example.expensetracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAk18G1nOGcFSstqgTdkXNuMpPzxNllC4U',
    appId: '1:920582359516:web:d8be57567c6de3a536e719',
    messagingSenderId: '920582359516',
    projectId: 'th5-mobile-4754a',
    authDomain: 'th5-mobile-4754a.firebaseapp.com',
    storageBucket: 'th5-mobile-4754a.firebasestorage.app',
    measurementId: 'G-46782M7QVP',
  );
}
